# parameter of the model
model_selection:
  model:
    XGBClassifier:
      search_param_grid:
        n_estimators: [100, 200]
        max_depth: [3, 5, 7]
        learning_rate: [0.01, 0.1]
    
    GradientBoostingClassifier:
      search_param_grid:
        n_estimators: [100, 200]
        max_depth: [3, 5]
        learning_rate: [0.01, 0.1]
    
    RandomForestClassifier:
      search_param_grid:
        n_estimators: [100, 200]
        max_depth: [5, 10, None]
        min_samples_split: [2, 5]